#!/usr/bin/env bash

# If we are running on any flavour of windows, don't set a theme
if [ $($DOTFILES_DIRECTORY/bin/is_win) == "yes" ]; then
    export VIM_BACKGROUND="dark"
    export VIM_THEME="NONE"

# Everyone else gets the default theme
else
    export VIM_BACKGROUND="dark"
    export VIM_THEME="base16-$BASE16_THEME"
fi

# vim: set syn=sh :
