#!/usr/bin/env bash

# This converts the input type of bash over to vim style
set -o vi

# Ensure that <C-l> Will clear the screen in insert mode
bind -m vi-insert 'Control-l: clear-screen'

# Determine if the git repo we are in has any changes in the working directory
function parse_git_dirty() {
    [[ $(git status 2> /dev/null | tail -n1) != *"working directory clean"* ]] && echo "*"
    # local git_status=$(git status 2> /dev/null | tail -n1)
    # [[ $git_status && $git_status != *"working directory clean"* ]] && echo "*"
}

# If the current directory belongs is a descendant of a git repo, determine the
# name of branch that is checked out
function parse_git_branch() {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
    # echo "$(git rev-parse --abbrev-ref HEAD 2> /dev/null)""$(parse_git_dirty)"
}

# Determine the look of our prompt. Eg
#
# whitneyit at MacBook in ~/Code/dotfiles on master
# $ echo "Hello world" > hi.txt
# whitneyit at MacBook in ~/Code/dotfiles on master*
# $
export PS1="\[${BOLD}${MAGENTA}\]\u \[$BLACK\]at \[$ORANGE\]\h \[$BLACK\]in \[$GREEN\]\w\[$BLACK\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$PURPLE\]\$(parse_git_branch)\[$BLACK\]\n\$ \[$RESET\]"
export PS1="\[${BOLD}${MAGENTA}\]\u \[$WHITE\]at \[$ORANGE\]\h \[$WHITE\]in \[$GREEN\]\w\[$WHITE\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$PURPLE\]\$(parse_git_branch)\[$WHITE\]\n\$ \[$RESET\]"
export PS2="\[$ORANGE\]→ \[$RESET\]"

# vim: set syn=sh :
