#!/usr/bin/env bash

# Set the global editor as vim
export EDITOR="vim"
export VISUAL="vim"

# Automatically trim long paths in the prompt (requires Bash 4.x)
export PROMPT_DIRTRIM="0"

# Perform file completion in a case insensitive fashion
bind "set completion-ignore-case on"

# Treat hyphens and underscores as equivalent
bind "set completion-map-case on"

# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"

# vim: set syn=sh :
