#!/usr/bin/env bash

export prev_http_proxy="http://user:password@website.com:1234"
export prev_https_proxy="http://user:password@website.com:1234"
export http_proxy=""
export https_proxy=""

# vim: set syn=sh :
