#!/usr/bin/env bash

# Here we define our language settings
export LANGUAGE="en_AU"
export LANG="en_AU"

# Here we change the way files are sorted
export LC_ALL="en_AU"
export LC_COLLATE="en_AU"
export LC_CTYPE="en_AU"
export LC_MESSAGES="en_AU"
export LC_MONETARY="en_AU"
export LC_NUMERIC="en_AU"
export LC_TIME="en_AU"

# Set the charset for the `less` command
export LESSCHARSET="UTF-8"

# vim: set syn=sh :
