#!/usr/bin/env bash

# If $DOTFILES_DIRECTORY is zero length then source `.bash_profile`
if [ -z "$DOTFILES_DIRECTORY" ]; then
    if [ -f "$DOTFILES_DIRECTORY/.bash_profile" ]; then
        source "$HOME/.bash_profile"
    fi
fi

# vim: set syn=sh :
