#!/usr/bin/env bash

# Record the previous directory
pwd > "$HOME/.prev_dir"

# when leaving the console clear the screen to increase privacy
if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

# vim: set syn=sh :
