#!/usr/bin/env bash

# Define some variables for our base16 theme
export BASE16_THEME="default"
export BASE16_VARIANT="dark"
export BASE16_FILE="base16-$BASE16_THEME.$BASE16_VARIANT.sh"
export BASE16_DIRECTORY="$DOTFILES_DIRECTORY/shell/base16-shell"

# When the active base16 theme is located
export BASE16_ACTIVE_THEME_PATH="$BASE16_DIRECTORY/$BASE16_FILE"

# Set the global editor as vim
export EDITOR='vim'
export VISUAL='vim'

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# This gives history entries a matching timestamp
export HISTTIMEFORMAT="%Y-%m-%d %T  "

# Here we define our language settings
export LANGUAGE=en_AU.UTF-8
export LANG=en_AU.UTF-8

# Here we change the way files are sorted
export LC_ALL="C"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# It seems that ChromeOS does not play nice with 256 colors. Until that is
# resolved, it looks like we can't use 256 color mode there.
if [ "$(is_chromeos)" == "no" ]; then

    # Set 256 color profile where possible
    if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
        export TERM=gnome-256color
    elif infocmp xterm-256color >/dev/null 2>&1; then
        export TERM=xterm-256color
    fi

fi

# vim: set syn=sh :
