#!/usr/bin/env bash

# This converts the input type of bash over to vim style
set -o vi

# Ensure that <C-l> Will clear the screen in insert mode
bind -m vi-insert 'Control-l: clear-screen'

# And also in command mode
bind -m vi-command 'Control-l: clear-screen'

# If we are running on any flavour of windows, don't set a theme
if [ $($DOTFILES_DIRECTORY/bin/is_win) == "yes" ]; then
    export VIM_BACKGROUND="dark"
    export VIM_THEME="NONE"

# If we are using the Apple terminal, don't set a theme
elif [ "$TERM_PROGRAM" == "Apple_Terminal" ]; then
    export VIM_BACKGROUND="dark"
    export VIM_THEME="NONE"

# If no base16 theme has been set, don't set a theme for vim
elif [ -z "$BASE16_THEME" ]; then
    export VIM_BACKGROUND="dark"
    export VIM_THEME="NONE"

# Everyone else gets the base16 theme
else
    export VIM_BACKGROUND="dark"
    export VIM_THEME="base16-$BASE16_THEME"
fi

# vim: set syn=sh :
