#!/usr/bin/env bash

# Here we determine the location of the `.dotfiles` repo
if [ -L $HOME/.dotfiles ]; then
    DOTFILES_DIRECTORY=$(readlink $HOME/.dotfiles)
else
    DOTFILES_DIRECTORY=$HOME/.dotfiles
fi

# Now we make the variable globally accesible
export DOTFILES_DIRECTORY

# And here we boot of the scripts
source $DOTFILES_DIRECTORY/bin/sauce

# This converts the input type of bash over to vim style
set -o vi

# Ensure that <C-l> Will clear the screen in insert mode
bind -m vi-insert 'Control-l: clear-screen'

# vim: set syn=sh :
