#!/usr/bin/env bash

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
export HISTCONTROL="ignoreboth"

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE="500000"

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history"

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE="100000"

# This gives history entries a matching timestamp
export HISTTIMEFORMAT="$(echo -e $GREEN) [%a %d %b %Y %H:%M:%S %z] $(echo -e $RESET)"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# vim: set syn=sh :
