#!/bin/bash

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/bin"
    "$HOME/bin"
    "$DOTFILES_DIRECTORY/bin"
)

for index in "${dirs_to_prepend[@]}"
do
    if [ -d $index ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${index}:$PATH"
    fi
done

# Append directories to PATH
for index in "${dirs_to_append[@]}"
do
    if [ -d $index ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${index}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH

# vim: set syn=sh :
