#!/usr/bin/env bash

# Ensure that we have a default environment set for node
export NODE_ENV="development"

# Define where we will be doing our `go` development
if [ "$(is_cygwin)" == "yes" ]; then
    export GOPATH="$(cygpath -wa $HOME/Code/go)"
    export GOHOME="/cygdrive/C/Go"
fi

# Configure the Java environment
if [ "$(is_mac)" == "yes" ]; then
    export JAVA_HOME="$(/usr/libexec/java_home 2>/dev/null)"
    export JDK_HOME="$(/usr/libexec/java_home 2>/dev/null)"
fi

# Define where the android platform tools live
if [ "$(is_mac)" == "yes" ]; then
    export ANDROID_TOOLS="$HOME/Library/Android/sdk"
fi

# vim: set syn=sh :
