#!/usr/bin/env bash

# Directories to be prepended to PATH
# Ensure that this bin always takes precedence over `/usr/bin`
declare -a DIRS_TO_PREPEND=(
    "./vendor/bin"
    "$HOME/bin"
    "$HOME/.composer/vendor/bin"
    "$HOME/.deno/bin"
    "$HOME/.dvm/bin"
    "$HOME/.npm-global/bin"
    "$HOME/.rvm/bin"
    "$GOROOT/bin"
    "$GOPATH/bin"
    "/usr/local/bin"
    "/usr/local/sbin"
    "/usr/local/heroku/bin"
    "/usr/local/opt/curl/bin"
    "/opt/homebrew/bin"
    "/opt/homebrew/sbin"
    "$JAVA_HOME/bin"
    "$ANDROID_HOME/tools"
    "$ANDROID_HOME/platform-tools"
)

# Directories to be appended to PATH
declare -a DIRS_TO_APPEND=(
    "/sbin"
    "/usr/bin"
    "/usr/local"
)

# Directories to be appended to PATH only when `is_mac` is true
declare -a MAC_DIRS_TO_APPEND=(
    "/usr/local/opt/git/share/git-core/contrib/diff-highlight"
    "$HOME/Library/Python/3.9/bin"
)

to_append=""
to_prepend=""

# Build up directions to prepend to PATH
for index in "${DIRS_TO_PREPEND[@]}"
do
    to_prepend="${to_prepend}:${index}"
done

to_prepend="${to_prepend:1}:"

# Build up directions to append to PATH
for index in "${DIRS_TO_APPEND[@]}"
do
    to_append="${to_append}:${index}"
done

# Now that we have sorted out $PATH, we can do platform specific stuff
PATH="${to_prepend}${PATH}${to_append}"

# Append the Mac directories
if [ "$(is_mac)" == "yes" ]; then
    for index in "${MAC_DIRS_TO_APPEND[@]}"
    do
        PATH="$PATH:${index}"
    done
fi

# Unset the Array variables
unset DIRS_TO_PREPEND
unset DIRS_TO_APPEND
unset MAC_DIRS_TO_PREPEND

# Export the `$PATH` variable
export PATH

# vim: set syn=sh :
