#!/usr/bin/env bash

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

#
if [ $(os) == "CYGWIN" ]; then

    # Complete foo.exe as foo, not foo.exe
    shopt -s completion_strip_exe

fi

# vim: set syn=sh :
