#!/usr/bin/env bash

# Example
# $ echo -e "$GREEN$RED_BACKGROUND"foo

# Define the "reset" colour
export RESET="\033[0m"

# Define the "modifier" colours
export BOLD="\033[1m"
export DIM="\033[2m"
export UNDERLINED="\033[4m"
export BLINK="\033[5m"
export REVERSE="\033[7m"
export HIDDEN="\033[8m"

export RESET_BOLD="\e[21m"
export RESET_DIM="\e[22m"
export RESET_UNDERLINED="\e[24m"
export RESET_BLINK="\e[25m"
export RESET_REVERSE="\e[27m"
export RESET_HIDDEN="\e[28m"

# Define the foreground colours
export BLACK="\033[0;30m"
export RED="\033[0;31m"
export GREEN="\033[0;32m"
export YELLOW="\033[0;33m"
export BLUE="\033[0;34m"
export MAGENTA="\033[0;35m"
export CYAN="\033[0;36m"
export WHITE="\033[0;37m"

# Define the bright foreground colours
export BRIGHT_BLACK="\033[1;30m"
export BRIGHT_RED="\033[1;31m"
export BRIGHT_GREEN="\033[1;32m"
export BRIGHT_YELLOW="\033[1;33m"
export BRIGHT_BLUE="\033[1;34m"
export BRIGHT_MAGENTA="\033[1;35m"
export BRIGHT_CYAN="\033[1;36m"
export BRIGHT_WHITE="\033[1;37m"

# Define the background colours. Note, there are no "bright" background colours
export BLACK_BACKGROUND="\033[40m"
export RED_BACKGROUND="\033[41m"
export GREEN_BACKGROUND="\033[42m"
export YELLOW_BACKGROUND="\033[43m"
export BLUE_BACKGROUND="\033[44m"
export MAGENTA_BACKGROUND="\033[45m"
export CYAN_BACKGROUND="\033[46m"
export WHITE_BACKGROUND="\033[47m"

# vim: set syn=sh :
