#!/usr/bin/env bash

# Directories to be prepended to PATH
# Ensure that this bin always takes precedence over `/usr/bin`
declare -a dirs_to_prepend=(
    "/usr/local/bin"
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/bin"
    "$DOTFILES_DIRECTORY/bin"
    "$HOME/bin"
    "$HOME/.composer/vendor/bin"
    "./vendor/bin"
)

# Prepend directories to PATH
for index in "${dirs_to_prepend[@]}"
do
    PATH="${index}:$PATH"
done

# Append directories to PATH
for index in "${dirs_to_append[@]}"
do
    PATH="$PATH:${index}"
done

# Unset the Array variables
unset dirs_to_prepend
unset dirs_to_append

# Export the `$PATH` variable
export PATH

# vim: set syn=sh :
