#!/usr/bin/env bash

# @gf3’s Sexy Bash Prompt, inspired by “Extravagant Zsh Prompt”
# Shamelessly copied from https://github.com/gf3/dotfiles
# Screenshot: http://i.imgur.com/s0Blh.png

# Set 256 color profile where possible
if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

if tput setaf 1 &> /dev/null; then
    tput sgr0
    if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
        BLACK=$(tput setaf 0)
        MAGENTA=$(tput setaf 9)
        ORANGE=$(tput setaf 172)
        GREEN=$(tput setaf 190)
        PURPLE=$(tput setaf 141)
        WHITE=$(tput setaf 255)
    else
        BLACK=$(tput setaf 0)
        MAGENTA=$(tput setaf 5)
        ORANGE=$(tput setaf 4)
        GREEN=$(tput setaf 2)
        PURPLE=$(tput setaf 1)
        WHITE=$(tput setaf 7)
    fi
    BOLD=$(tput bold)
    RESET=$(tput sgr0)
else
    BLACK="\033[1;30m"
    MAGENTA="\033[1;31m"
    ORANGE="\033[1;33m"
    GREEN="\033[1;32m"
    PURPLE="\033[1;35m"
    WHITE="\033[1;37m"
    BOLD=""
    RESET="\033[m"
fi

export BLACK
export MAGENTA
export ORANGE
export GREEN
export PURPLE
export WHITE
export BOLD
export RESET

# Base16 Default - Shell color setup script
# Chris Kempson (http://chriskempson.com)

# Define where our base16 colour scheme is found
export BASE16_SHELL="$DOTFILES_DIRECTORY/shell/bash_shell"

# This script doesn't support linux console (use 'vconsole' template instead)
if [ "${TERM%%-*}" = 'linux' ]; then
    return 2>/dev/null || exit 0
fi

color00="18/18/18"          # Base 00 - Black
color01="ab/46/42"          # Base 08 - Red
color02="a1/b5/6c"          # Base 0B - Green
color03="f7/ca/88"          # Base 0A - Yellow
color04="7c/af/c2"          # Base 0D - Blue
color05="ba/8b/af"          # Base 0E - Magenta
color06="86/c1/b9"          # Base 0C - Cyan
color07="d8/d8/d8"          # Base 05 - White
color08="58/58/58"          # Base 03 - Bright Black
color09=$color01            # Base 08 - Bright Red
color10=$color02            # Base 0B - Bright Green
color11=$color03            # Base 0A - Bright Yellow
color12=$color04            # Base 0D - Bright Blue
color13=$color05            # Base 0E - Bright Magenta
color14=$color06            # Base 0C - Bright Cyan
color15="f8/f8/f8"          # Base 07 - Bright White
color16="dc/96/56"          # Base 09
color17="a1/69/46"          # Base 0F
color18="28/28/28"          # Base 01
color19="38/38/38"          # Base 02
color20="b8/b8/b8"          # Base 04
color21="e8/e8/e8"          # Base 06
color_foreground="d8/d8/d8" # Base 05
color_background="18/18/18" # Base 00
color_cursor="d8/d8/d8"     # Base 05

# Tell tmux to pass the escape sequences through
# (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
if [ -n "$TMUX" ]; then
    printf_template="\033Ptmux;\033\033]4;%d;rgb:%s\007\033\\"
    printf_template_var="\033Ptmux;\033\033]%d;rgb:%s\007\033\\"

# GNU screen (screen, screen-256color, screen-256color-bce)
elif [ "${TERM%%-*}" = "screen" ]; then
    printf_template="\033P\033]4;%d;rgb:%s\007\033\\"
    printf_template_var="\033P\033]%d;rgb:%s\007\033\\"

# Something else?
else
    printf_template="\033]4;%d;rgb:%s\033\\"
    printf_template_var="\033]%d;rgb:%s\033\\"
fi

# 16 color space
printf $printf_template 0  $color00
printf $printf_template 1  $color01
printf $printf_template 2  $color02
printf $printf_template 3  $color03
printf $printf_template 4  $color04
printf $printf_template 5  $color05
printf $printf_template 6  $color06
printf $printf_template 7  $color07
printf $printf_template 8  $color08
printf $printf_template 9  $color09
printf $printf_template 10 $color10
printf $printf_template 11 $color11
printf $printf_template 12 $color12
printf $printf_template 13 $color13
printf $printf_template 14 $color14
printf $printf_template 15 $color15

# 256 color space
printf $printf_template 16 $color16
printf $printf_template 17 $color17
printf $printf_template 18 $color18
printf $printf_template 19 $color19
printf $printf_template 20 $color20
printf $printf_template 21 $color21

# foreground / background / cursor color
# printf $printf_template_var 10 $color_foreground
# printf $printf_template_var 11 $color_background
# printf $printf_template_var 12 $color_cursor

# clean up
unset printf_template
unset printf_template_var
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background
unset color_cursor

# vim: set syn=sh :
