#!/usr/bin/env bash

# Here we ensure that the `.prev_dir` file is created so that our interactive
# shells are smart about where they need to return to.
if [ ! -f $HOME/.prev_dir ]; then

    # Since the file does not exist, we can create it now.
    touch $HOME/.prev_dir

    # Now if we want to change the permissions on the file in `cygwin` we need
    # to first change the "group" to `Users`.
    if [ $(os) == "CYGWIN" ]; then
        chgrp Users $HOME/.prevdir
    fi

    # Now we update the permissions on the file
    chmod 755 $HOME/.prev_dir

fi

# vim: set syn=sh :
