#!/usr/bin/env bash

# If running bash
if [ -n "$BASH_VERSION" ]; then

    # If $DOTFILES_DIRECTORY is a zero length string then we know that we
    # have not run our `.bash_profile` setup
    if [ -z "$DOTFILES_DIRECTORY" ] || [ ! "$(type -P prompt_command)" ]; then

        # Ensure that some base colors are exported
        LS_COLORS="ow=01;36;40"
        export LS_COLORS

        # Run our `.bash_profile` setup
        if [ -f "$HOME/.bash_profile" ]; then
            source "$HOME/.bash_profile"
        fi

    fi

fi

# vim: set syn=sh :
