#!/bin/bash

# Set user-defined locale
export LANG=$(locale -uU)

# If running bash
if [ -n "${BASH_VERSION}" ]; then
	if [ -f "${HOME}/.bashrc" ]; then
		source "${HOME}/.bashrc"
	fi
fi


# vim: set syn=sh :
