#!/usr/bin/env bash

# Add a `.html` extension to `text/html` or `application/xhtml+xml` files that
# lack one, or a `.css` extension to `text/css` files that lack one
adjust_extension = on

# When set to off, this will disallow server-caching
cache = off

# Defines headers to be sent accross with the request
header = Connection: Keep-Alive
header = Accept-Language: en

# Retry even when the connection was refused.
retry_connrefused = on

# Setting this to off makes Wget not download /robots.txt
robots = off

# Don't wait too long before timing out. This applies to all timeouts: DNS,
# connect and read. (The default read timeout is 15 minutes!)
timeout = 30

# Use the server-provided last modified date, if available
# timestamping = on # Disabled because of collision with babun. `pact install` fails

# Retry a few times when a download fails, but don't overdo it. (Default is 20!)
tries = 3

# Spoof a user-agent
user_agent = Konqueror

# vim: set syn=sh :
