#!/usr/bin/env bash

#
if [ is_cygwin == "yes" ]; then

    #
    if [ -d /cygdrive/c ]; then
        alias c="cd /cygdrive/c"
        alias pf32="cd /cygdrive/c/Program\ Files\ \(x86\)/"
        alias pf64="cd /cygdrive/c/Program\ Files\/"
    fi

    #
    if [ -d /cygdrive/d ]; then
        alias d="cd /cygdrive/d"
    fi

    #
    if [ -e /dev/clipboard ]; then
        alias pbcopy="cat >/dev/clipboard"
        alias pbpaste="cat /dev/clipboard"
    fi

    #
    alias open="cygstart"

    #
    alias d2u="find . -type f -exec dos2unix {} \;"

fi

# vim: set syn=sh :
