#!/bin/bash

#
if [ $(os) == "CYGWIN" ]; then

	#
	alias ls="ls \
	-G \
	-h \
	--color \
	--group-directories-first \
	--ignore='bootmgr' \
	--ignore='BOOTNXT' \
	--ignore='hiberfil.sys' \
	--ignore='pagefile.sys' \
	--ignore='swapfile.sys' \
	--ignore='ntuser*' \
	--ignore='NTUSER*' \
	--ignore='\$Recycle\.Bin' \
	--ignore='\$RECYCLE\.BIN' \
	--ignore='System\ Volume\ Information'"

	#
	if [ -d /cygdrive/c ]; then
		alias c="cd /cygdrive/c"
	fi

	#
	if [ -d /cygdrive/d ]; then
		alias d="cd /cygdrive/d"
	fi

	#
	alias open="cygstart"

	#
	alias d2u="find . -type f -exec dos2unix {} \;"

fi

# vim: set syn=sh :
