#!/usr/bin/env bash

# This is just a quick way of jumping up directories
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# Quickly jump to some system folders
alias desktop="cd ~/Desktop/"
alias downloads="cd ~/Downloads/"
alias documents="cd ~/Documents/"
alias dropbox="cd ~/Dropbox/"
alias sites="cd ~/Sites/"

# And now dev folders
alias code="cd ~/Code/"
alias dev="cd ~/Dev/"
alias setup="cd ~/Code/setup/"
alias snippets="cd ~/Code/snippets/"
alias vg="cd ~/Code/vagrant/"

# And finally lets make an alias back to this repo
function df() {
    cd "$DOTFILES_DIRECTORY"
}

# vim: set syn=sh :
