#!/bin/bash

alias code="cd ~/Code/"
alias desktop="cd ~/Desktop/"
alias downloads="cd ~/Downloads/"
alias documents="cd ~/Documents/"
alias dropbox="cd ~/Dropbox/"
alias sites="cd ~/Sites/"

# vim: set syn=sh :
