#!/usr/bin/env bash

# This is just a quick way of jumping up directories
alias        ..="cd ../"
alias       ...="cd ../../"
alias      ....="cd ../../../"
alias     .....="cd ../../../../"

# Quickly jump to some system folders
alias   desktop="cd ~/Desktop/"
alias downloads="cd ~/Downloads/"
alias documents="cd ~/Documents/"
alias   dropbox="cd ~/Dropbox/"
alias     sites="cd ~/Sites/"

# Dev folders
alias   archive="cd ~/Archive/"
alias      code="cd ~/Code/"
alias       dev="cd ~/Dev/"

# Project folders
alias     setup="cd ~/Code/setup/"
alias  snippets="cd ~/Code/snippets/"
alias   taskify="cd ~/Code/gulp-taskify/"
alias        vg="cd ~/Code/vagrant/"

# And finally lets make an alias back to this repo
alias        df="cd "$DOTFILES_DIRECTORY""

# vim: set syn=sh :
