#!/bin/bash

alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# We do not want to overwrite our cygwin specific ls
if [ $(os) != "CYGWIN" ]; then
	alias  ls="ls -hG"
fi

alias  ll="ls -ll"
alias  la="ls -la"
alias lsd="ls -d */"
alias lld="ls -lld */"
alias lad="ls -lad */"

# Allow my windows muscle memmory to be a bit more forgiving
alias cls="clear"
alias dir="ls -la"

# vim: set syn=sh :
