#!/bin/bash

alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# We do not want to overwrite our cygwin specific ls
if [ $(os) != "CYGWIN" ]; then
	alias  ls="ls -hG"
fi

# Improve `ls`
alias  ll="ls -ll"
alias  la="ls -la"
alias lsd="ls -d */"
alias lld="ls -lld */"
alias lad="ls -lad */"

# Quick way to convert spaces to tabs, and vicer versa
alias s2t="find ./ -type f -exec sed -i 's/\    /\t/g' {} \;"
alias t2s="find ./ -type f -exec sed -i 's/\t/    /g' {} \;"

# Allow my windows muscle memmory to be a bit more forgiving
alias cls="clear"
alias dir="ls -la"

# vim: set syn=sh :
