#!/bin/bash

alias vbp="vim ~/.dotfiles/shell/bash_profile"
alias vrc="vim ~/.dotfiles/vim/vimrc"
alias vrcb="vim ~/.dotfiles/vim/vimrc_bundle"

alias desktop="cd ~/Desktop/"
alias downloads="cd ~/Downloads/"
alias dropbox="cd ~/Dropbox/"
alias sites="cd ~/Sites/"

alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"

# We do not want to overwrite our cygwin specific ls
if [ $(os) != "CYGWIN" ]; then
	alias  ls="ls --color --group-directories-first"
fi

alias  ll="ls -ll"
alias  la="ls -la"
alias lsd="ls -d */"
alias lld="ls -lld */"
alias lad="ls -lad */"

# Allow my windows muscle memmory to be a bit more forgiving
alias cls="clear"
alias dir="ls -la"

# vim: set syn=sh :
