#!/usr/bin/env bash

alias    ga="git add"
alias   gaa="git add --all ."
alias   gap="git add --patch"
alias   gbl="git blame --show-number --show-email"
alias   gbr="git branch"
alias  gbrl="git branch --all --verbose" # -a -v, -av
alias  gbrd="git branch --delete" # -d, or -D to ignore merge status
alias gbrdf="git branch -D" # Force delete
alias grblw="git for-each-ref --sort=-committerdate refs/remotes/ --format='%(authordate) %09 %(refname:short)'"
alias   gcf="git config"
alias  gcfl="git config --list"
alias   gco="git checkout"
alias  gcom="git checkout master"
alias  gcod="git checkout develop"
alias  gcob="git checkout -b" # no such thing as --branch
alias  gcop="git checkout --patch" # -p
alias  gcoa="git checkout ." # This is a fake alias to git checkout --all which does not exist
alias   gcl="git clone"
alias   gcn="git clean -dfxn"
alias  gcnf="git clean -dfx"
alias   gcm="git commit --verbose" # -v
alias  gcms="git commit --verbose --message" # -v -m, -vm
alias  gcma="git commit --verbose --amend"
alias    gd="git diff --word-diff"
alias   gds="git diff --word-diff --cached"
alias   gin="git init"
alias    gf="git fetch --progress --verbose"
alias   gig="git ls-files --ignored --exclude-standard"
alias   gla="git log --no-merges                        --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias  glda="git log --no-merges                --patch --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias  glsa="git log --no-merges                --stat  --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias  glga="git log                            --graph --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias  glia="git log                                    --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'    ..@{upstream}"
alias glida="git log                            --patch --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'    ..@{upstream}"
alias glisa="git log                            --stat  --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d %n' ..@{upstream}"
alias gliga="git log                            --graph --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'    ..@{upstream}"
alias  gloa="git log --branches --not --remotes         --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias glosa="git log --branches --not --remotes --stat  --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias gloda="git log --branches --not --remotes --patch --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias gloga="git log --branches --not --remotes --graph --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias    gm="git merge --no-ff --progress --verbose"
alias   gmu="git merge --no-ff --progress --verbose @{upstream}"
alias   gps="git push          --progress --verbose"
alias  gpsf="git push          --progress --verbose --force"
alias  gpsd="git push          --progress --verbose --delete"
alias   gpl="git pull          --progress --verbose"
alias   grb="git rebase"
alias  grfa="git reflog         --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias grfsa="git reflog --stat  --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias grfda="git reflog --patch --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias grfga="git reflog --graph --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias   grs="git reset"
alias grshd="git reset --hard 'HEAD^'"
alias  grsh="git reset HEAD --"
alias  grss="git reset --soft 'HEAD^'"
alias  grsp="git reset --patch"
alias   grm="git rm"
alias  grmc="git rm --cached"
alias grmca="git rm --cached -r ."
alias   gmo="git status --porcelain | cut -c 4-"
alias   gsm="git submodule"
alias  gsma="git submodule add"
alias  gsmu="git submodule update --recursive --init"
alias   gsh="git show --no-merges        --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias  gshs="git show --no-merges --stat --pretty=format:'%C(yellow)%h %C(green)[%cr] %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias   gst="git status --untracked-files=all"
alias  gsti="git status --untracked-files=all --ignored"
alias   gsg="git stage"

# Here we just define a few shortcuts to modify the author of a commit. This can
# be used when you forget to setup the local author details
alias  gcfa="git commit --amend --reset-author"
alias  gcfe="git config user.email "
alias  gcfn="git config user.name "

# A quick way to update the url of a repo
alias  gcfo="git remote set-url origin "

# Logging shortcuts
alias    gl="gla   -10"
alias   gls="glsa  -10"
alias   gld="glda  -10"
alias   glg="glga  -10"

# Incoming commits
alias   gli="glia  -10"
alias  glis="glisa -10"
alias  glid="glida -10"
alias  glig="gliga -10"

# Outgoing commits
alias   glo="gloa  -10"
alias  glos="glosa -10"
alias  glod="gloda -10"
alias  glog="gloga -10"

# Reflogs
alias   grf="grfa  -10"
alias  grfs="grfsa -10"
alias  grfd="grfda -10"
alias  grfg="grfga -10"

# Here we protect against typos
alias  gacm="gcma"
alias  glsg="glgs"
alias glsga="glgsa"

# vim: set syn=sh :
