#!/bin/bash

alias   gfl="git flow"
alias  gflh="git flow help"
alias  gfli="git flow init"
alias  gflf="git flow feature"
alias gflfs="git flow feature start"
alias gflff="git flow feature finish"
alias  gflh="git flow hotfix"
alias gflhs="git flow hotfix start"
alias gflhf="git flow hotfix finish"
alias  gflr="git flow release"
alias gflrs="git flow release start"
alias gflrf="git flow release finish"

# vim: set syn=sh :
