#!/usr/bin/env bash

# Because `cygwin` has a more enhanced version of `ls` we will target it
# directly. The "--ignores" that you see below are just there to exclude some
# system files that shouldn't be showing up anyways.
if [ $(os) == "CYGWIN" ]; then

    alias ls="ls \
    -h \
    --color \
    --group-directories-first \
    --ignore='bootmgr' \
    --ignore='BOOTNXT' \
    --ignore='hiberfil.sys' \
    --ignore='pagefile.sys' \
    --ignore='swapfile.sys' \
    --ignore='ntuser*' \
    --ignore='NTUSER*' \
    --ignore='\$Recycle\.Bin' \
    --ignore='\$RECYCLE\.BIN' \
    --ignore='System\ Volume\ Information'"

else
    alias  ls="ls -h --color"
fi

# This is a command that will output a numeric versios of the file permissions
OCTAL_PERMISSIONS="{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}"

function ll () {
    ls -l  $1 | awk "$OCTAL_PERMISSIONS" | tail -n +2
}

function la () {
    ls -la $1 | awk "$OCTAL_PERMISSIONS" | tail -n +2
}

function ld () {
    ls -lad . .. */ $1 | awk "$OCTAL_PERMISSIONS"
}

function lf () {
    ls -la $1 | grep -v '^d' | awk "$OCTAL_PERMISSIONS" | tail -n +2
}

# vim: set syn=sh :
