#!/bin/bash

#
if [ $(os) == "CYGWIN" ]; then

    alias ls="ls \
    -h \
    -G \
    --color \
    --group-directories-first \
    --ignore='bootmgr' \
    --ignore='BOOTNXT' \
    --ignore='hiberfil.sys' \
    --ignore='pagefile.sys' \
    --ignore='swapfile.sys' \
    --ignore='ntuser*' \
    --ignore='NTUSER*' \
    --ignore='\$Recycle\.Bin' \
    --ignore='\$RECYCLE\.BIN' \
    --ignore='System\ Volume\ Information'"

else
    alias  ls="ls -h -G --color"
fi

# Improve `ls`
alias ll="ls -l      | awk '{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}'"
alias la="ls -la     | awk '{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}'"
alias ld="ls -lad */ | awk '{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}'"

# vim: set syn=sh :
