#!/usr/bin/env bash

# Quick way to convert spaces to tabs, and vicer versa
alias s2ta="find ./ -type f -exec sed -i 's/    /\t/g' {} \;"
alias t2sa="find ./ -type f -exec sed -i 's/\t/    /g' {} \;"

# Use this command for a single file, and the above, for a collection
alias  s2t="sed -i 's/    /\t/g'"
alias  t2s="sed -i 's/\t/    /g'"

# vim: set syn=sh :
