#!/usr/bin/env bash

alias   vi="vim"
alias   vm="vim"
alias  vbp="vim ~/.bash_profile"

function vrc() {

    if [ -f .vimrc.local ]; then
        vim .vimrc.local
    elif [ -f .vimrc ]; then
        vim .vimrc
    else
        vim ~/.vimrc
    fi

}

# vim: set syn=sh :
