#!/usr/bin/env bash

alias   vi="vim"
alias   vm="vim"
alias  vbp="vim $DOTFILES_DIRECTORY/shell/bash_profile"
alias  vrc="vim $DOTFILES_DIRECTORY/vim/vimrc"
alias vrcb="vim $DOTFILES_DIRECTORY/vim/vimrc_bundle"
alias vrcc="vim $DOTFILES_DIRECTORY/vim/vimrc_commands"
alias vrcl="vim $DOTFILES_DIRECTORY/vim/vimrc_leaders"
alias vrcm="vim $DOTFILES_DIRECTORY/vim/vimrc_mappings"

# vim: set syn=sh :
