" Disable vi-compatibility
set nocompatible

" Point to location of pathogen submodule (since it's not in .vim/autoload)
silent! runtime bundle/vim-pathogen/autoload/pathogen.vim

" Call pathogen plugin management
silent! call pathogen#infect()

" This generates all the "pathogen" plugin helptags
silent! call pathogen#helptags()

if has("autocmd")

    " Load files for specific filetypes
    filetype on
    filetype indent on
    filetype plugin on

    " Ensure the correct filetypes are used
    autocmd BufNewFile,BufRead *.cshtml    set filetype=html
    autocmd BufNewFile,BufRead *.eslintrc  set filetype=json
    autocmd BufNewFile,BufRead *.jslintrc  set filetype=json
    autocmd BufNewFile,BufRead *.md        set filetype=markdown
    autocmd BufNewFile,BufRead *.rb        set filetype=ruby
    autocmd BufNewFile,BufRead Vagrantfile set filetype=ruby

    " Automatically strip trailing whitespace on file save
    autocmd BufWritePre * :call StripTrailingWhitespace()

endif

if has("syntax")

    " Enable syntax highlighting
    syntax on

    " Set 256 color terminal support
    set t_Co=256

endif

if has("cmdline_info")

    " Show the cursor line and column number
    set ruler

    " Show partial commands in status line
    set showcmd

    " Show whether in insert or replace mode
    set noshowmode

endif

if has("statusline")

    " Always show status line
    set laststatus=2

    " Broken down into easily includeable segments
    set statusline=%<%f\

    " Options
    set statusline+=%w%h%m%r

    " Current dir
    set statusline+=\ [%{getcwd()}]

    " Right aligned file nav info
    set statusline+=%=%-14.(%l,%c%V%)\ %p%%

endif

if has("extra_search")

    " Highlight searches [use :noh to clear]
    set hlsearch

    " Highlight dynamically as pattern is typed
    set incsearch

    " Ignore case of searches...
    set ignorecase

    " ...unless has mixed case
    set smartcase

endif

" Set the colorscheme
colorscheme xoria256
" colorscheme molokai

" Set a vertical column only on the lines that bleed over
call matchadd('ColorColumn', '\%81v', 100)

" Determines the maximum amount of tabs to be used before we start falling
" back to buffers
set tabpagemax=1000

" Record undo actions even after files are closed
set undofile

" Make substitution global inside a line
set gdefault

" This considers 0 prefixed numbers as decimal
set nrformats-=octal

" Set the title for xterm
set title

" Set to auto read when a file is changed from the outside
set autoread

" Backspace through everything in INSERT mode
set backspace=indent,eol,start

" Optimize for fast terminal connections
set ttyfast

" Use UTF-8 without BOM
set encoding=utf-8 nobomb

" Inform vim of the current shell
set shell=bash

" No line wrapping
set nowrap

" But when we enter wrap mode, make sure that we dont break on words
set linebreak

" Enable line numbers
set number

" Highlight current line
set cursorline

" Start scrolling three lines before the horizontal window border
set scrolloff=3

" Don't reset cursor to start of line when moving around.
set nostartofline

" Removes top toolbar
set guioptions-=T

" Removes right hand scroll bar
set guioptions-=r

" Removes left hand scroll bar
set guioptions-=L

" Sets the lineheight
set linespace=15

" Define our tags file
set tags=tags

" Always set autoindenting on
set autoindent

" This indents deeper per code block, eg an `if statement`
set smartindent

" Copy the previous indentation on autoindenting
set copyindent

" Convert tab to spaces
set expandtab

" Define some default tab widths
set tabstop=4
set softtabstop=4
set shiftwidth=4

" When using `>` and `<`, this will indent to multiple of `shiftwidth` and not
" just add to it. Eg an indent of 10 spaces will become 12
set shiftround

" Timeout stuff
set timeout
set timeoutlen=300
set ttimeoutlen=300

" Don't beep
set visualbell
set noerrorbells

" Save on buffer switch
set autowrite

" Hide 'invisible' characters
set nolist

" Set characters used to indicate 'invisible' characters
set listchars=tab:▸\-
set listchars+=trail:·
set listchars+=nbsp:_
set listchars+=eol:¬

" Enable the wildmenu
set wildmenu
set wildmode=list:longest

" Make sure these directories are not included in the results panel
set wildignore+=*/.git/**
set wildignore+=*/.vagrant/**
set wildignore+=*/node_modules/**

" Centralize backups, swapfiles and undo history
set backupdir=$HOME/.vim/backups
set directory=$HOME/.vim/swaps
if exists("&undodir")
    set undodir=$HOME/.vim/undo
endif
set viminfo+=n$HOME/.vim/.viminfo

" Turn backup off, since most stuff is in git anyway. The above stuff is just
" so we get the folder structure correct so if we ever turn swaps on, they
" don't pollute our local directories
set nobackup
set nowb
set noswapfile

" Easier window navigation
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" Load up our other keybinds
source $HOME/.vim/vimrc_abbr
source $HOME/.vim/vimrc_commands
source $HOME/.vim/vimrc_functions
source $HOME/.vim/vimrc_keybinds
source $HOME/.vim/vimrc_bundle

" Load local machine settings if they exist
if filereadable(glob("$HOME/.vimrc.local"))
    source $HOME/.vimrc.local
endif

" Load up any project specific settings
if filereadable(glob("$PWD/.vimrc.local"))
    source $PWD/.vimrc.local
endif
