#!/usr/bin/env bash
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
DIR="`git rev-parse --git-dir`"
trap 'rm -f "$DIR/$$.tags"' EXIT
git ls-files | ctags --tag-relative -L - -f"$DIR/$$.tags" --languages=-javascript,sql
mv "$DIR/$$.tags" "$DIR/tags"

# vim: set syn=sh :
