#!/usr/bin/env bash

fnd() {
    find * \
        -not -path ".chrome/**"          -not -path "**/.chrome/**" \
        -not -path ".git/**"             -not -path "**/.git/**" \
        -not -path ".hg/**"              -not -path "**/.hg/**" \
        -not -path ".karma/**"           -not -path "**/.karma/**" \
        -not -path ".protractor/**"      -not -path "**/.protractor/**" \
        -not -path ".sass-cache/**"      -not -path "**/.sass-cache/**" \
        -not -path ".svn/**"             -not -path "**/.svn/**" \
        -not -path "backups/**"          -not -path "**/backups/**" \
        -not -path "bower_components/**" -not -path "**/bower_components/**" \
        -not -path "bundle/**"           -not -path "**/bundle/**" \
        -not -path "completions/**"      -not -path "**/completions/**" \
        -not -path "coverage/**"         -not -path "**/coverage/**" \
        -not -path "dist/**"             -not -path "**/dist/**" \
        -not -path "docs/**"             -not -path "**/docs/**" \
        -not -path "jspm_packages/**"    -not -path "**/jspm_packages/**" \
        -not -path "node_modules/**"     -not -path "**/node_modules/**" \
        -not -path "plugins/**"          -not -path "**/plugins/**" \
        -not -path "reports/**"          -not -path "**/reports/**" \
        -not -path "typings/**"          -not -path "**/typings/**" \
        -not -path "undo/**"             -not -path "**/undo/**" \
        -not -path "vendor/**"           -not -path "**/vendor/**" \
        "$@" \
        | sort
}

fndd() {
    find * \
        -not -path ".chrome/**"          -not -path "**/.chrome/**" \
        -not -path ".git/**"             -not -path "**/.git/**" \
        -not -path ".hg/**"              -not -path "**/.hg/**" \
        -not -path ".karma/**"           -not -path "**/.karma/**" \
        -not -path ".protractor/**"      -not -path "**/.protractor/**" \
        -not -path ".sass-cache/**"      -not -path "**/.sass-cache/**" \
        -not -path ".svn/**"             -not -path "**/.svn/**" \
        -not -path "backups/**"          -not -path "**/backups/**" \
        -not -path "bower_components/**" -not -path "**/bower_components/**" \
        -not -path "bundle/**"           -not -path "**/bundle/**" \
        -not -path "completions/**"      -not -path "**/completions/**" \
        -not -path "coverage/**"         -not -path "**/coverage/**" \
        -not -path "dist/**"             -not -path "**/dist/**" \
        -not -path "docs/**"             -not -path "**/docs/**" \
        -not -path "jspm_packages/**"    -not -path "**/jspm_packages/**" \
        -not -path "node_modules/**"     -not -path "**/node_modules/**" \
        -not -path "plugins/**"          -not -path "**/plugins/**" \
        -not -path "reports/**"          -not -path "**/reports/**" \
        -not -path "typings/**"          -not -path "**/typings/**" \
        -not -path "undo/**"             -not -path "**/undo/**" \
        -not -path "vendor/**"           -not -path "**/vendor/**" \
        -type d -iname "$1" \
        | sort
}

fndf() {
    find * \
        -not -path ".chrome/**"          -not -path "**/.chrome/**" \
        -not -path ".git/**"             -not -path "**/.git/**" \
        -not -path ".hg/**"              -not -path "**/.hg/**" \
        -not -path ".karma/**"           -not -path "**/.karma/**" \
        -not -path ".protractor/**"      -not -path "**/.protractor/**" \
        -not -path ".sass-cache/**"      -not -path "**/.sass-cache/**" \
        -not -path ".svn/**"             -not -path "**/.svn/**" \
        -not -path "backups/**"          -not -path "**/backups/**" \
        -not -path "bower_components/**" -not -path "**/bower_components/**" \
        -not -path "bundle/**"           -not -path "**/bundle/**" \
        -not -path "completions/**"      -not -path "**/completions/**" \
        -not -path "coverage/**"         -not -path "**/coverage/**" \
        -not -path "dist/**"             -not -path "**/dist/**" \
        -not -path "docs/**"             -not -path "**/docs/**" \
        -not -path "jspm_packages/**"    -not -path "**/jspm_packages/**" \
        -not -path "node_modules/**"     -not -path "**/node_modules/**" \
        -not -path "plugins/**"          -not -path "**/plugins/**" \
        -not -path "reports/**"          -not -path "**/reports/**" \
        -not -path "typings/**"          -not -path "**/typings/**" \
        -not -path "undo/**"             -not -path "**/undo/**" \
        -not -path "vendor/**"           -not -path "**/vendor/**" \
        -type f -iname "$1" \
        | sort
}

# vim: set syn=sh :
