#!/usr/bin/env bash

# If we have hub installed, alias it now
if [ "$(type -P hub)" ]; then
    alias git="hub"
fi

alias    ga="git add"
alias   gaa="git add --all ."
alias   gap="git add --patch"
alias   gbl="git blame --show-number --show-email"
alias   gbr="git branch"
alias  gbrl="git branch --all --verbose" # -a -v, -av
alias  gbrd="git branch --delete" # -d, or -D to ignore merge status
alias gbrdf="git branch -D" # Force delete
alias   gcf="git config"
alias  gcfl="git config --list"
alias   gco="git checkout"
alias  gcom="git checkout master"
alias  gcod="git checkout develop"
alias  gcob="git checkout -b" # no such thing as --branch
alias  gcop="git checkout --patch" # -p
alias  gcoa="git checkout ." # This is a fake alias to git checkout --all which does not exist
alias   gcl="git clone"
alias   gcn="git clean -dfxn"
alias  gcnf="git clean -dfx"
alias   gcm="git commit --verbose" # -v
alias  gcms="git commit --verbose --message" # -v -m, -vm
alias  gcma="git commit --verbose --amend"
alias gcmas="git commit --verbose --amend --message"
alias gcmac="git commit --verbose --amend --no-edit"
alias    gd="git diff"
alias   gds="git diff --cached"
alias   gdt="git difftool"
alias    gh="git stash"
alias   ghp="git stash pop"
alias   gin="git init"
alias    gf="git fetch --progress --verbose"
alias   gla="git log --no-merges                        --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias  glfa="git log --no-merges                        --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d' develop.."
alias  glda="git log --no-merges                --patch --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias  glsa="git log --no-merges                --stat  --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias  glma="git log --merges                           --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias  glga="git log                            --graph --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias  glia="git log                                    --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'    ..@{upstream}"
alias glida="git log                            --patch --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'    ..@{upstream}"
alias glisa="git log                            --stat  --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d %n' ..@{upstream}"
alias gliga="git log                            --graph --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'    ..@{upstream}"
alias  gloa="git log --branches --not --remotes         --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias glosa="git log --branches --not --remotes --stat  --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias gloda="git log --branches --not --remotes --patch --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias gloga="git log --branches --not --remotes --graph --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias    gm="git merge --no-ff --progress --verbose"
alias   gma="git merge --abort"
alias   gmd="git merge --no-ff --progress --verbose develop"
alias   gmu="git merge --no-ff --progress --verbose @{upstream}"
alias   gps="git push          --progress --verbose"
alias  gpsf="git push          --progress --verbose --force"
alias  gpsd="git push          --progress --verbose --delete"
alias   gpl="git pull          --progress --verbose"
alias  gplf="git pull          --progress --verbose --force"
alias   grb="git rebase"
alias  grba="git rebase --abort"
alias  grbi="git rebase --interactive"
alias  grbc="git rebase --continue"
alias  grfa="git reflog         --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d'"
alias grfsa="git reflog --stat  --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias grfda="git reflog --patch --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias grfga="git reflog --graph --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(blue)%gs %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias   grs="git reset"
alias grshd="git reset --hard 'HEAD^'"
alias  grsh="git reset HEAD --"
alias  grss="git reset --soft 'HEAD^'"
alias  grsp="git reset --patch"
alias   grm="git rm"
alias  grmc="git rm --cached"
alias grmca="git rm --cached -r ."
alias   gsm="git submodule"
alias  gsma="git submodule add"
alias  gsmc="git submodule foreach --recursive git checkout ."
alias  gsmu="git submodule update --recursive --init"
alias   gsh="git show --no-merges        --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias  gshs="git show --no-merges --stat --date=iso --pretty=format:'%C(yellow)%h %C(green)[%ad] %C(cyan)%ae %C(reset)%s %C(white)%d %n'"
alias   gst="git status --untracked-files=all"
alias  gsti="git status --untracked-files=all --ignored"
alias    gv="git --version"

# Here we just define a few shortcuts to modify the author of a commit. This can
# be used when you forget to setup the local author details
alias  gcfa="git commit --amend --reset-author"
alias  gcfe="git config user.email "
alias  gcfn="git config user.name "

# A quick way to update the url of a repo
alias  gcfo="git remote set-url origin "

# A way to see modified files
alias   gmo="git status --porcelain | cut -c 4-"

# List ignored files
alias   gig="git ls-files --ignored --exclude-standard"

# Updates the indexed `stat` of a file. It does not modify the file though
# normally this means that you will have to check out the file after updating
# the index. Git only respects files of `stat` 644 or 755. Yea it's weird...
alias  g644="git update-index --chmod=-x"
alias  g755="git update-index --chmod=+x"

# Logging shortcuts
alias    gl="gla   -10"
alias   gls="glsa  -10"
alias   gld="glda  -10"
alias   glg="glga  -10"
alias   glm="glma  -10"
alias   glf="glfa  -10"

# Incoming commits
alias   gli="glia  -10"
alias  glis="glisa -10"
alias  glid="glida -10"
alias  glig="gliga -10"

# Outgoing commits
alias   glo="gloa  -10"
alias  glos="glosa -10"
alias  glod="gloda -10"
alias  glog="gloga -10"

# Reflogs
alias   grf="grfa  -10"
alias  grfs="grfsa -10"
alias  grfd="grfda -10"
alias  grfg="grfga -10"

# Here we protect against typos
alias  gacm="gcma"
alias  gmca="gcma"
alias  gscm="gcms"
alias  gmcs="gcms"
alias  glsg="glgs"
alias glsga="glgsa"

# vim: set tw=0:syn=sh :
