#!/usr/bin/env bash

# Makes using `grep` all that much easier. Where;
# i: case insensitive
# r: recursive
# F: makes grep search with a string instead of regex
# l: list of filenames instead of contexts
alias   grp="grep --color -inF"
alias  grpr="grep --color -inrF"
alias  grpl="grep --color -inFl"
alias grprl="grep --color -inrFl"

# Allow for typos
alias grplr="greprl"

# vim: set syn=sh :
