#!/usr/bin/env bash

ARGS="\
    --color \
    --exclude *.lock \
    --exclude *.map \
    --exclude *.min.css \
    --exclude *.min.js \
    --exclude *.svg \
    --exclude *lock.json \
    --exclude npm-debug.log \
    --exclude-dir .cache \
    --exclude-dir .chrome \
    --exclude-dir .git \
    --exclude-dir .hg \
    --exclude-dir .karma \
    --exclude-dir .protractor \
    --exclude-dir .sass-cache \
    --exclude-dir .svn \
    --exclude-dir backups \
    --exclude-dir bower_components \
    --exclude-dir build \
    --exclude-dir bundle \
    --exclude-dir completions \
    --exclude-dir coverage \
    --exclude-dir dist \
    --exclude-dir docs \
    --exclude-dir graph \
    --exclude-dir jspm_packages \
    --exclude-dir node_modules \
    --exclude-dir out-tsc \
    --exclude-dir plugins \
    --exclude-dir reports \
    --exclude-dir tmp \
    --exclude-dir typings \
    --exclude-dir undo \
    --exclude-dir vendor \
    "

# I: ignore binary files
# i: case insensitive
# l: list of filenames instead of contexts
# n: line number
# P: Perl-compatible regular expression
# R: recursive
# z: Treat the input as a set of lines

alias    grp="ggrep -I       -i    -n    $ARGS"
alias   grpl="ggrep -I       -i -l       $ARGS"
alias   grpm="ggrep -I -P -z -i    -n    $ARGS"
alias   grps="ggrep -I             -n    $ARGS"
alias  grpls="ggrep -I          -l       $ARGS"
alias  grpms="ggrep -I -P -z       -n    $ARGS"
alias   grpr="ggrep -I       -i    -n -R $ARGS"
alias  grprl="ggrep -I       -i -l    -R $ARGS"
alias  grprm="ggrep -I -P -z -i    -n -R $ARGS"
alias  grprs="ggrep -I             -n -R $ARGS"
alias grprls="ggrep -I          -l    -R $ARGS"
alias grprms="ggrep -I -P -z       -n -R $ARGS"

# vim: set syn=sh :
