#!/usr/bin/env bash

# Makes using `grep` all that much easier. Where;
# I: ignore binary files
# i: case insensitive
# n: line number
# l: list of filenames instead of contexts
# r: recursive

alias    grp="grep -I -i -n    --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"
alias   grpl="grep -I -i -l    --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"
alias   grps="grep -I    -n    --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"
alias  grpls="grep -I    -l    --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"
alias   grpr="grep -I -i -n -r --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"
alias  grprl="grep -I -i -l -r --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"
alias  grprs="grep -I    -n -r --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"
alias grprls="grep -I    -l -r --color --exclude *.map --exclude npm-debug.log --exclude-dir .git --exclude-dir .karma --exclude-dir .protractor --exclude-dir .sass-cache --exclude-dir bower_components --exclude-dir bundle --exclude-dir coverage --exclude-dir dist --exclude-dir docs --exclude-dir jspm_packages --exclude-dir node_modules --exclude-dir reports --exclude-dir typings --exclude-dir vendor"

# vim: set syn=sh :
