#!/usr/bin/env bash

yarn-exists() {
    if [ ! "$(type -P yarn)" ]; then
        echo 0
    elif [ ! -f "$(type -P yarn)" ]; then
        echo 0
    else
        echo 1
    fi
}

ni() {
    if [ "$#" == "0" ]; then
        echo -e "$BRIGHT_BLACK$ npm install$RESET"
        npm install
    else
        echo -e "$BRIGHT_BLACK$ npm install --save "$@"$RESET"
        npm install --save "$@"
    fi
}

nid() {
    echo -e "$BRIGHT_BLACK$ npm install --save-dev "$@"$RESET"
    npm install --save-dev "$@"
}

nig() {
    echo -e "$BRIGHT_BLACK$ npm install --global "$@"$RESET"
    npm install --global "$@"
}

nu() {
    echo -e "$BRIGHT_BLACK$ npm uninstall --save "$@"$RESET"
    npm uninstall --save "$@"
}

nud() {
    echo -e "$BRIGHT_BLACK$ npm uninstall --save-dev "$@"$RESET"
    npm uninstall --save-dev "$@"
}

nug() {
    echo -e "$BRIGHT_BLACK$ npm uninstall --global "$@"$RESET"
    npm uninstall --global "$@"
}

ns() {
    echo -e "$BRIGHT_BLACK$ npm start "$@"$RESET"
    npm start "$@"
}

nt() {
    echo -e "$BRIGHT_BLACK$ npm test "$@"$RESET"
    npm test "$@"
}

nl() {
    echo -e "$BRIGHT_BLACK$ npm list --depth=0 "$@"$RESET"
    npm list --depth=0 "$@"
}

nlg() {
    echo -e "$BRIGHT_BLACK$ npm list --global --depth=0 "$@"$RESET"
    npm list --global --depth=0 "$@"
}

nupgrade() {
    echo "upgrading npm..."
    curl http://npmjs.org/install.sh | sudo sh
}

nv() {
    if [ ! -z "$NVM_DIR" ]; then
        if [ "$(is_win)" == "yes" ]; then
            echo "nvm  v$(nvm version)"
        else
            echo "nvm  v$(nvm --version)"
        fi
    else
        echo "nvm [not installed]"
    fi
    if [ "$(type -P node)" ]; then
        echo "node $(node --version)"
    else
        echo "node [not installed]"
    fi
    if [ "$(type -P npm)" ]; then
        echo "npm  v$(npm --version)"
    else
        echo "npm  [not installed]"
    fi
    if [ "$(yarn-exists)" == "1" ]; then
        echo "yarn $(yarn --version)"
    else
        echo "yarn [not installed]"
    fi
}

ngp() {
    readlink -f "$(which ${1:-npm})"
}

ngd() {
    path="$(ngp $1)"
    echo "$(dirname "$path")"
}

if [ "$(is_win)" == "yes" ]; then
    alias npm="cmd /c npm"
fi

# vim: set tw=0:syn=sh :
