#!/usr/bin/env bash

alias  ni="npm install"
alias nig="npm install --global"
alias nis="npm install --save"
alias nid="npm install --save-dev"
alias  nl="npm list --depth=0"
alias nlg="npm list --depth=0 --global"
alias  np="npm prune"
alias  ns="npm start"
alias  nt="npm test"
alias  nu="npm uninstall"
alias nus="npm uninstall --save"
alias nud="npm uninstall --save-dev"
alias nug="npm uninstall --global"

nv() {
    echo nvm version $(nvm --version)
    echo node version $(node --version)
    echo npm version $(npm --version)
}

ngp() {
    readlink -f "$(which ${1:-npm})"
}

if [ "$(is_win)" == "yes" ]; then
    alias npm="cmd /c npm"
fi

# vim: set tw=0:syn=sh :
