#!/usr/bin/env bash

ARGS="\
    --dirsfirst \
    -I ' \
    |.chrome| \
    |.git| \
    |.hg| \
    |.karma| \
    |.protractor| \
    |.sass-cache| \
    |.svn| \
    |backups| \
    |bower_components| \
    |build| \
    |bundle| \
    |completions| \
    |coverage| \
    |dist| \
    |docs| \
    |graph| \
    |jspm_packages| \
    |node_modules| \
    |out-tsc| \
    |plugins| \
    |reports| \
    |tmp| \
    |typings| \
    |undo| \
    |vendor| \
    '"

# a: all files
# d: directories only
# L: depth

alias   tre="tree -a         $ARGS"
alias  tred="tree -a -d      $ARGS"

alias  tre1="tree -a    -L 1 $ARGS"
alias tred1="tree -a -d -L 1 $ARGS"

# vim: set syn=sh :
