#!/usr/bin/env bash

function run_help() {

cat <<EOT

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text

Copyright (c) James Whitney <james@whitney.io>
Licensed under the MIT license.
EOT

}

# vim: set syn=sh :
