#!/usr/bin/env bash

alias  amt="cd ~/Code/AMT"
alias amtf="cd ~/Code/amt-framework"
alias amtw="cd ~/Code/AMT/AmtWeb/AmtWeb.Mvc"

if [ "$(is_cygwin)" == "yes" ]; then
    alias  amt="cd /cygdrive/c/GIT/AMT"
    alias amtw="cd /cygdrive/c/GIT/AMT/AmtWeb/AmtWeb.Mvc"
fi

# vim: set syn=sh :
