#!/usr/bin/env bash

# Aliases to the git repos
alias  asc="cd ~/Code/amp-styleguide-core"
alias ascm="cd ~/Code/amp-styleguide-core-mine"
alias  asw="cd ~/Code/amp-styleguide-website"
alias  cpc="cd ~/Code/CustomerPortalCSS"

# vim: set syn=sh :
