#!/usr/bin/env bash

# Aliases to the git repos
alias  ghw="cd ~/Code/gh2_websites"
alias  gha="cd ~/Code/glasshat-v2"
alias  ghb="cd ~/Code/ghbox"
alias ghbm="cd ~/Code/ghboxmake"

# vim: set syn=sh :
