#!/usr/bin/env bash

# Aliases to the git repos
alias tempest="cd ~/Code/tempest"
alias storm="cd ~/Code/storm"

# Here we define a function used to deploy our changes to fortrabbit
function tempest-deploy() {

    # Here we define the `git commit` message
    MESSAGE="*Tempest deployed* at $(date +%Y-%m-%d) $(date +%T)"

    # Make an empy commit marking the time the commit was done
    git commit --allow-empty -m "$MESSAGE"

    # If the composer flag was passed in, mark that here
    if [[ "$1" == "-c" || "$1" == "--composer" ]]; then
        git commit --allow-empty -m '[trigger:composer]'
    fi

    # Push the repo to where it needs to go
    git push origin --all
    git push fortrabbit master

}

# vim: set syn=sh :
