#!/usr/bin/env bash

# Project folders
alias boilerplate="cd ~/Code/boilerplate/"
alias          de="cd ~/Code/detect-environment"
alias   homestead="cd ~/Code/homestead"
alias       pages="cd ~/Code/whitneyit.github.io/"
alias       setup="cd ~/Code/setup/"
alias    snippets="cd ~/Code/snippets/"
alias     taskify="cd ~/Code/gulp-taskify/"
alias          vg="cd ~/Code/vagrant/"

# Here we define a dynamic alias  to our "dotfiles" directory
alias        df="cd "$DOTFILES_DIRECTORY""

# vim: set syn=sh :
