#!/bin/bash

chrome() {

	# This needs to be updated to get the absolute windows style path
	FILE_PATH=$1

	if [ $(os) == "CYGWIN" ]; then
		open /cygdrive/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe $FILE_PATH
	elif [ $(os) == "Mac" ]; then
		open -a Google\ Chrome "$1"
	fi
	
}

# vim: set syn=sh :
