#!/usr/bin/env bash

# Because `cygwin` has a more enhanced version of `ls` we will target it
# directly. The "--ignores" that you see below are just there to exclude some
# system files that shouldn't be showing up anyways.
if [ "$(is_cygwin)" == "yes" ]; then

    #
    function list () {

        #
        command ls \
            -h \
            --color \
            --ignore="bootmgr" \
            --ignore="BOOTNXT" \
            --ignore="hiberfil.sys" \
            --ignore="pagefile.sys" \
            --ignore="swapfile.sys" \
            --ignore="ntuser*" \
            --ignore="NTUSER*" \
            --ignore="\$Recycle\.Bin" \
            --ignore="\$RECYCLE\.BIN" \
            --ignore="System\ Volume\ Information" \
            "$1"
    }

#
else

    #
    function list () {

        #
        command ls\
            -h \
            -G \
            "$1"
    }

fi

# This is a command that will output a numeric versios of the file permissions
OCTAL_PERMISSIONS="{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}"

#
function ls () {
    list .
}

#
function ll () {
    list -l              | awk "$OCTAL_PERMISSIONS"
}

#
function la () {
    list -la | grep "^d" | awk "$OCTAL_PERMISSIONS" && \
    list -la | grep "^l" | awk "$OCTAL_PERMISSIONS" && \
    list -la | grep "^-" | awk "$OCTAL_PERMISSIONS"
}

#
function ld () {
    list -la | grep "^d" | awk "$OCTAL_PERMISSIONS"
}

#
function lf () {
    list -la | grep "^l" | awk "$OCTAL_PERMISSIONS" && \
    list -la | grep "^-" | awk "$OCTAL_PERMISSIONS"
}

# vim: set syn=sh :
