#!/usr/bin/env bash

# This is just a quick way of jumping up directories
alias        ..="cd ../"
alias       ...="cd ../../"
alias      ....="cd ../../../"
alias     .....="cd ../../../../"
alias    ......="cd ../../../../../"
alias   .......="cd ../../../../../../"
alias  ........="cd ../../../../../../../"
alias .........="cd ../../../../../../../../"

# Quickly jump to some system folders
alias   desktop="cd ~/Desktop/"
alias  pictures="cd ~/Pictures/"
alias documents="cd ~/Documents/"
alias downloads="cd ~/Downloads/"

# Protect against typings
alias        dc="cd"
alias       cd-="cd -"

# vim: set syn=sh :
