#!/usr/bin/env bash

# Ensure that these aliases are only ever processed if we are in an mac box.
if [ "$(is_mac)" == "yes" ]; then

    # If we have installed gnu dircolors via homebrew, alias that now.
    if [ "$(type -P gdircolors)" ]; then
        alias dircolors="gdircolors"
    fi

    # If we have installed gnu grep via homebrew, alias that now.
    if [ "$(type -P ggrep)" ]; then
        alias grep="ggrep"
    fi

    # If we have installed gnu readlink via homebrew, alias that now.
    if [ "$(type -P greadlink)" ]; then
        alias readlink="greadlink"
    fi

    # If we have installed gnu sed via homebrew, alias that now.
    if [ "$(type -P gsed)" ]; then
        alias sed="gsed"
    fi

    # If we have installed gnu sort via homebrew, alias that now.
    if [ "$(type -P gsort)" ]; then
        alias sort="gsort"
    fi

fi

# vim: set syn=sh :
