#!/usr/bin/env bash

# Ensure that these aliases are only ever processed if we are in a ChromeOS box.
if [ "$(is_ubuntu)" == "yes" ]; then

    # Check to make sure the lightbar exists
    if [ -f "/sys/devices/platform/cros_ec_lpc.0/cros-ec-dev.0/chromeos/cros_ec/lightbar/sequence" ]; then

        # Now lets make the lightbar flask the konami code
        alias konami="echo 'konami' > /sys/devices/platform/cros_ec_lpc.0/cros-ec-dev.0/chromeos/cros_ec/lightbar/sequence"

    fi

    # Replace the `open` command with `gnome-open`. This requires installing
    # the `libgnome2-bin` binary.
    if [ ! "$(type -P gnome-open)" ]; then
        sudo apt-get install -y libgnome2-bin
    fi

    # Now use gnome
    alias open="gnome-open"

    # If we have wine installed creat some aliases to games
    if [ "$(type -P wine)" ]; then
        alias battle="LIBGL_ALWAYS_SOFTWARE=1 wine '$HOME/.PlayOnLinux/wineprefix/Battle.net/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe'"
    fi

fi

# vim: set syn=sh :
